#!/usr/bin/env bash
# configures ubuntu server, localhost and facebook.com
sudo cp /etc/hosts ~/hosts.new
sudo sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8     facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
